### ISSUE TITLE
RuntimeError: symeig_cuda: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1001).

### ISSUE THREAD

**Issue by ghost** [alexfrom0815/Online-3D-BPP-DRL#9]
Hi,

The training runs successfuly however, I get that error after a few hrs of training.

Full error trace:

Traceback (most recent call last):
  File "main.py", line 270, in <module>
    main(args)
  File "main.py", line 42, in main
    train_model()
  File "main.py", line 223, in train_model
    value_loss, action_loss, dist_entropy, prob_loss, graph_loss = agent.update(rollouts)
  File "/home/Online-3D-BPP-DRL-main/acktr/algo/acktr_pipeline.py", line 98, in update
    self.optimizer.step()
  File "/home/lib/python3.6/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/Online-3D-BPP-DRL-main/acktr/algo/kfac.py", line 216, in step
    self.m_aa[m], eigenvectors=True)
RuntimeError: symeig_cuda: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1001)

**Comment by alexfrom0815** [comment]
> Hi,
> 
> The training runs successfuly however, I get that error after a few hrs of training.
> 
> Full error trace:
> 
> Traceback (most recent call last): File "main.py", line 270, in main(args) File "main.py", line 42, in main train_model() File "main.py", line 223, in train_model value_loss, action_loss, dist_entropy, prob_loss, graph_loss = agent.update(rollouts) File "/home/Online-3D-BPP-DRL-main/acktr/algo/acktr_pipeline.py", line 98, in update self.optimizer.step() File "/home/lib/python3.6/site-packages/torch/optim/optimizer.py", line 88, in wrapper return func(*args, **kwargs) File "/home/Online-3D-BPP-DRL-main/acktr/algo/kfac.py", line 216, in step self.m_aa[m], eigenvectors=True) RuntimeError: symeig_cuda: The algorithm failed to converge because the input matrix is ill-conditioned or has too many repeated eigenvalues (error code: 1001)

Hi, unfortunately there seem to be many unknown reasons for this error, so I recommend you to use our new repo (https://github.com/alexfrom0815/Online-3D-BPP-PCT), this version is more stable to train and will definitely improve your user experience.

**Comment by codebear99** [comment]
Hi,

Thank you for the information.

When are you going to share the codes for "Learning Practically Feasible
Policies for Online 3D Bin Packing"? Are you planning to do that?

**Comment by alexfrom0815** [comment]
Thank you for your attention. In fact, there is not much difference between the network model of 'Online 3D Bin Packing with Constrained Deep Reinforcement Learning' and "Learning Practically Feasible Policies for Online 3D Bin Packing". The contribution of the latter is more in the construction of real machine scenarios, so I will not plan to organize the code of the latter at present.

**Comment by codebear99** [comment]
Thank you, I have looked at that.

I just needed a small clarification about "Learning Practically Feasible
Policies for Online 3D Bin Packing":
1. How do I calculate the conditional probability? Also, do you use a
MultiCategorical distribution to combine the individual logits
2. Can you just share some snapshot of the code for the actor head eg
./acktr/model.py's forward() &/or ./acktr/distributions.py in case you are
using MultiCategorical. Just these two files would be enough even if they
are organised, that's fine.

Thanks in advance.

Regards
